# Cena-An Automated Menu Planner {#Cena}

#### Abstract {-}

(ref:abs1)

#### Keywords {-}

menu, menu planning, shopping list, food, dinner, meal, problem solver, we have to eat again

## Do we really have to eat again?

The daily struggle to come up with a dinner solution is real for anyone who eats. Meal planning can help solve the problem by providing a simple plan to follow every night.

But, let's be honest, putting together a meal plan takes hours! First, you sift through the multitudes of online recipes. Next, you become overwhelmed but get to work. After several iterations you're sweating, but you have a meal plan, and you can meticulously check ingredient lists to put together a weekly shopping list. After all that, you need a nap! 

Enter Cena, a foodie best friend that hands you a list of personalized recipes and guides you with a shopping list. [@nikolaus_family_2017][@seyitoglu_conceptual_2016]


## Welcome Cena, your menu navigator.

Cena will scour recipe websites and deliver a personalized menu plan along with a shopping list.  

To get to know you, as the eater, Cena will ask about basic dietary restrictions (Vegetarian, vegan, gluten free, Kosher, Halal, etc.). Then you will get to play a quick game of "Would you rather eat this or that?". Based on the responses to this game, and ratings by users like you, Cena will combine individual recipes and present your first meal plan. 

After getting to know the food preferences of those for whom you meal plan, Cena will take off scraping the web for recipes every week.  Using an algorithm yet-to-be-determined[@v_science_nodate], it will rank recipes, and select a handful for a complete week of meals.  After you approve the suggestion, Cena will compile a shopping list based on the recipe ingredient lists. Cena practically holds your hand at the grocery store. 

Since Cena can access the entire internet of recipes, it is not limited in the meal plans it can create.  Cena will work equally well for a single young professional or a large family with kids and grandparents, for a nutrition buff following a strict diet or a comfort food lover.  Even though you may not explicitly state your food health goals, such as lowering cholesterol, Cena will soon learn them if you are honest with your feedback.

Based on the meals you queue for certain evenings, Cena will learn your typical dining schedule.  However, if you choose, you can let Cena know that you usually eat alone on Tuesdays, eat out on Fridays, and need to please a crowd for lunch every other Sunday.
   
Cena will use machine learning to incorporate your ratings of individual meals and overall plans with those of similar users to carefully curate your next meal plan. Do you enjoy simple meals with few ingredients?  Do you love fancy meals that wow all your guests? Do you consistently rate simple, light-colored, carb-heavy meals highly because you are a toddler? The more you use it, the better Cena will know you. Cena will balance your food preferences with your stated food aspirations.


## What will you do with your free time?

Over time, Cena will learn your preferences. It will plan meals that evoke your childhood or delightfully surprise you by pushing your epicurean boundaries, all while meeting your needs. Cena might miss the mark, though if it does not get accurate feedback. Though someone may want or need to limit their sodium intake, Cena cannot force them to enjoy low sodium meals. But if Cena ever gets it wrong, you can easily swap out a meal or a whole plan for something different.

Best of all, it will remove the mountain of small decisions from your day, easing the decision fatigue and freeing up your time and energy to tackle the big stuff. [@tierney_you_2011]


